caption: Control the enablement of <ph name="GEN_AI_WALLPAPER_FEATURE_NAME">"GenAI Wallpaper"</ph> feature in <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph>
desc: |-
  This policy enables or disables <ph name="GEN_AI_WALLPAPER_FEATURE_NAME">"GenAI Wallpaper"</ph> for <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph>.
  0 = Do not allow <ph name="GEN_AI_WALLPAPER_FEATURE_NAME">"GenAI Wallpaper"</ph>.

  1 = Allow <ph name="GEN_AI_WALLPAPER_FEATURE_NAME">"GenAI Wallpaper"</ph> without improving AI models.

  If this policy is set to Unset, <ph name="GEN_AI_WALLPAPER_FEATURE_NAME">"GenAI Wallpaper"</ph> feature is allowed without improving AI models for enterprise and EDU users.
  In M127, the policy was disabled for enterprise users by default.
default: 1
example_value: 0
features:
  dynamic_refresh: true
  per_profile: true
owners:
- file://ash/webui/personalization_app/OWNERS
items:
- caption: Do not allow "GenAI Wallpaper"
  name: Disabled
  value: 0
- caption: Allow "GenAI Wallpaper" without improving AI models
  name: AllowedWithoutLogging
  value: 1
schema:
  enum:
  - 0
  - 1
  type: integer
supported_on:
- chrome_os:127-
tags: []
type: int-enum